/*
	OxyWeatherStation.m
	The implementation classes and methods for the OxyWeatherStation web service.
	Generated by SudzC.com
*/

#import "OxyWeatherStation.h"
				
#import "Soap.h"
	

/* Implementation of the service */
				
@implementation OxyWeatherStation

	- (id) init
	{
		if(self = [super init])
		{
			self.serviceUrl = @"http://apps.oxy.edu/ws/OxyWeatherStation.asmx";
			self.namespace = @"http://apps.oxy.edu/webservices/";
			self.headers = nil;
			self.logging = NO;
		}
		return self;
	}
	
	- (id) initWithUsername: (NSString*) username andPassword: (NSString*) password {
		if(self = [super initWithUsername:username andPassword:password]) {
		}
		return self;
	}
	
	+ (OxyWeatherStation*) service {
		return [OxyWeatherStation serviceWithUsername:nil andPassword:nil];
	}
	
	+ (OxyWeatherStation*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password {
		return [[OxyWeatherStation alloc] initWithUsername:username andPassword:password];
	}

		
	/* Returns NSDate*.  */
	- (SoapRequest*) getLastUpdate: (id <SoapDelegate>) handler
	{
		return [self getLastUpdate: handler action: nil];
	}

	- (SoapRequest*) getLastUpdate: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getLastUpdate" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getLastUpdate" postData: _envelope deserializeTo: @"NSDate"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getTemperatureInCelsius: (id <SoapDelegate>) handler
	{
		return [self getTemperatureInCelsius: handler action: nil];
	}

	- (SoapRequest*) getTemperatureInCelsius: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getTemperatureInCelsius" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getTemperatureInCelsius" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getTemperatureInFahrenheit: (id <SoapDelegate>) handler
	{
		return [self getTemperatureInFahrenheit: handler action: nil];
	}

	- (SoapRequest*) getTemperatureInFahrenheit: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getTemperatureInFahrenheit" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getTemperatureInFahrenheit" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getHumidity: (id <SoapDelegate>) handler
	{
		return [self getHumidity: handler action: nil];
	}

	- (SoapRequest*) getHumidity: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getHumidity" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getHumidity" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getPressureInMilliBar: (id <SoapDelegate>) handler
	{
		return [self getPressureInMilliBar: handler action: nil];
	}

	- (SoapRequest*) getPressureInMilliBar: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getPressureInMilliBar" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getPressureInMilliBar" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getPressureInHgInches: (id <SoapDelegate>) handler
	{
		return [self getPressureInHgInches: handler action: nil];
	}

	- (SoapRequest*) getPressureInHgInches: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getPressureInHgInches" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getPressureInHgInches" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getSolarIntensityInWattsPerSqMeter: (id <SoapDelegate>) handler
	{
		return [self getSolarIntensityInWattsPerSqMeter: handler action: nil];
	}

	- (SoapRequest*) getSolarIntensityInWattsPerSqMeter: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getSolarIntensityInWattsPerSqMeter" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getSolarIntensityInWattsPerSqMeter" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getSolarIntensityInWattsPerSqFeet: (id <SoapDelegate>) handler
	{
		return [self getSolarIntensityInWattsPerSqFeet: handler action: nil];
	}

	- (SoapRequest*) getSolarIntensityInWattsPerSqFeet: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getSolarIntensityInWattsPerSqFeet" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getSolarIntensityInWattsPerSqFeet" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getWindSpeedInKmPerHour: (id <SoapDelegate>) handler
	{
		return [self getWindSpeedInKmPerHour: handler action: nil];
	}

	- (SoapRequest*) getWindSpeedInKmPerHour: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getWindSpeedInKmPerHour" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getWindSpeedInKmPerHour" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getWindSpeedInMiPerHour: (id <SoapDelegate>) handler
	{
		return [self getWindSpeedInMiPerHour: handler action: nil];
	}

	- (SoapRequest*) getWindSpeedInMiPerHour: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getWindSpeedInMiPerHour" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getWindSpeedInMiPerHour" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getWindDirection: (id <SoapDelegate>) handler
	{
		return [self getWindDirection: handler action: nil];
	}

	- (SoapRequest*) getWindDirection: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getWindDirection" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getWindDirection" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getRainInMillimeter: (id <SoapDelegate>) handler
	{
		return [self getRainInMillimeter: handler action: nil];
	}

	- (SoapRequest*) getRainInMillimeter: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getRainInMillimeter" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getRainInMillimeter" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}

	/* Returns double.  */
	- (SoapRequest*) getRainInInches: (id <SoapDelegate>) handler
	{
		return [self getRainInInches: handler action: nil];
	}

	- (SoapRequest*) getRainInInches: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getRainInInches" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://apps.oxy.edu/webservices/getRainInInches" postData: _envelope deserializeTo: @"double"];
		[_request send];
		return _request;
	}


@end
	