/*
	OxyWeatherStation.h
	The interface definition of classes and methods for the OxyWeatherStation web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				

/* Interface for the service */
				
@interface OxyWeatherStation : SoapService
		
	/* Returns NSDate*.  */
	- (SoapRequest*) getLastUpdate: (id <SoapDelegate>) handler;
	- (SoapRequest*) getLastUpdate: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getTemperatureInCelsius: (id <SoapDelegate>) handler;
	- (SoapRequest*) getTemperatureInCelsius: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getTemperatureInFahrenheit: (id <SoapDelegate>) handler;
	- (SoapRequest*) getTemperatureInFahrenheit: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getHumidity: (id <SoapDelegate>) handler;
	- (SoapRequest*) getHumidity: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getPressureInMilliBar: (id <SoapDelegate>) handler;
	- (SoapRequest*) getPressureInMilliBar: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getPressureInHgInches: (id <SoapDelegate>) handler;
	- (SoapRequest*) getPressureInHgInches: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getSolarIntensityInWattsPerSqMeter: (id <SoapDelegate>) handler;
	- (SoapRequest*) getSolarIntensityInWattsPerSqMeter: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getSolarIntensityInWattsPerSqFeet: (id <SoapDelegate>) handler;
	- (SoapRequest*) getSolarIntensityInWattsPerSqFeet: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getWindSpeedInKmPerHour: (id <SoapDelegate>) handler;
	- (SoapRequest*) getWindSpeedInKmPerHour: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getWindSpeedInMiPerHour: (id <SoapDelegate>) handler;
	- (SoapRequest*) getWindSpeedInMiPerHour: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getWindDirection: (id <SoapDelegate>) handler;
	- (SoapRequest*) getWindDirection: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getRainInMillimeter: (id <SoapDelegate>) handler;
	- (SoapRequest*) getRainInMillimeter: (id) target action: (SEL) action;

	/* Returns double.  */
	- (SoapRequest*) getRainInInches: (id <SoapDelegate>) handler;
	- (SoapRequest*) getRainInInches: (id) target action: (SEL) action;

		
	+ (OxyWeatherStation*) service;
	+ (OxyWeatherStation*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	