/*
	Services.h
	Creates a list of the services available with the  prefix.
	Generated by SudzC.com
*/
#import "OxyWeatherStation.h"

@interface Services : NSObject {
	BOOL logging;
	NSString* server;
	NSString* defaultServer;
OxyWeatherStation* oxyWeatherStation;

}

-(id)initWithServer:(NSString*)serverName;
-(void)updateService:(SoapService*)service;
-(void)updateServices;
+(Services*)service;
+(Services*)serviceWithServer:(NSString*)serverName;

@property (nonatomic) BOOL logging;
@property (nonatomic, retain) NSString* server;
@property (nonatomic, retain) NSString* defaultServer;

@property (nonatomic, retain, readonly) OxyWeatherStation* oxyWeatherStation;

@end
			